---
title: "`r SMRD2:::info('book')`"
subtitle: "`r SMRD2:::info('chapter5')`"
author: "`r SMRD2:::info('authors')`"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    css: my-vignette.css
    fig_caption: yes
vignette: >
  %\VignetteIndexEntry{echapter5}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, echo=FALSE}
SMRD2:::vinny()
library(SMRD2)
```

## Vignette Info

```{r}
distribution.plot2("Gamma",
                  shape = c( .8,1,2),
                  xlim = c(0,4))

distribution.plot2("Igau",
                  shape = c( 1,2,4),
                  plot.haz.log = F,
                  xlim = c(0,3),
                  prob.range = c(0.001, 0.99))

distribution.plot2("Bisa",
                  shape = c(.5,.6,.85,1),
                  plot.haz.log = F, 
                  prob.range = c(0.001, 0.95),
                  xlim = c(0,3))

distribution.plot2("Goma",
                  shape = c( .2,2,.2,2),
                  shape2 = c( .5,.5,3,3))
```

```{r, fig.width=8, fig.height=8}
SMRD2:::gets.pdf.plot()
```